name: udacity
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.7
  - pip
  - pandas>=1.0.3
  - pylint
  - pytest>=5.4.1
  - pytorch>=1.5.0
  - scikit-learn
  - scipy
  - torchvision
  - wheel
  - pip:
    - lightgbm>=2.3.1
    - requests
    - rope>=0.17
    - typeguard
