repositories:
- name: grafana
  url: https://grafana.github.io/helm-charts
- name: jaegertracing
  url: https://jaegertracing.github.io/helm-charts

releases:
# https://github.com/grafana/helm-charts
- name: grafana
  chart: grafana/grafana
  values:
    - single-binary-grafana-values.yaml
# https://grafana.com/docs/tempo/latest/setup/helm-chart/
# https://github.com/grafana/tempo/issues/624

# worked! http://grafana-tempo:3100/api/echo
- name: grafana-tempo
  chart: grafana/tempo
  # https://github.com/grafana/tempo/blob/main/example/helm/single-binary-grafana-values.yaml


# https://grafana.com/docs/agent/latest/operator/helm-getting-started/
# - name: grafana-agent
#   chart: grafana/grafana-agent-operator
# - name: jaeger
#   chart: jaegertracing/jaeger
