repositories:

  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: jaegertracing
    url: https://jaegertracing.github.io/helm-charts

releases:

  # https://github.com/grafana/helm-charts
  - name: grafana
    chart: grafana/grafana
    values:
      - single-binary-grafana-values.yaml

  # https://grafana.com/docs/tempo/latest/setup/helm-chart/
  - name: grafana-tempo
    chart: grafana/tempo
