# Nearly copy/pasted from:
# https://github.com/grafana/tempo/blob/main/example/helm/single-binary-grafana-values.yaml

env:
  GF_AUTH_ANONYMOUS_ENABLED: true
  GF_AUTH_ANONYMOUS_ORG_ROLE: 'Admin'
  GF_AUTH_DISABLE_LOGIN_FORM: true

datasources:
  datasources.yaml:
    apiVersion: 1

    datasources:
      - name: Tempo
        type: tempo
        access: proxy
        orgId: 1
        # Verify this URL by SSH'ing into another pod and running:
        # curl -v http://grafana-tempo:3100/api/echo
        # (https://github.com/grafana/tempo/issues/624)
        url: http://grafana-tempo:3100
        basicAuth: false
        isDefault: true
        version: 1
        editable: false
        apiVersion: 1
        uid: tempo
