# https://stackoverflow.com/a/56801559
# https://github.com/redhat-cop/openshift-templates/blob/master/secrets/secret-docker-cfg-stringdata.yml
# https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: ghcr
type: kubernetes.io/dockerconfigjson
stringData: 
  # https://blinkit.com/blog/adopting-tekton-cloud-native-ci-solution
  # https://dev.to/asizikov/using-github-container-registry-with-kubernetes-38fb
  # TODO: fortunately does NOT need
  # echo -n "dkmiller:$(op read op://Private/github.ptah/credential)" | base64
  # "auth": "(output above)"
  # https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  .dockerconfigjson: >-
    {
      "auths": {
        "ghcr.io": {
          "username": "dkmiller",
          "password": "op://Private/github.ptah/credential"
        }
      }
    }
