pipeline:
  client_id: XnkMHEYUujv1wA7EkmToWg
  client_secret: secret://reddit-client-secret
  subreddits: funny,gifs,news,pics
  output_file_name: data.json
  source_jsonpaths: $.title $.selftext
  source_key: text
  target_jsonpath: $.gilded
  target_key: label

aml:
  subscription_id: 48bbc269-ce89-4f6f-9a12-c6f91fcb772d
  resource_group_name: aml1p-rg
  workspace_name: aml1p-ml-wus2

logging:
  # https://github.com/Azure/azure-sdk-for-python/issues/9422
  azure.core.pipeline.policies.http_logging_policy: WARNING
