[project]
name = "rag"
version = "0.0.0"
dependencies = [
    "cache-decorator==2.1.15",
    "sentence-transformers==2.2.2",
    "typer==0.9.0",
]
[project.optional-dependencies]
dev = [
    "black==23.10.1",
]

[project.scripts]
rag = "rag.cli:main"
