# https://github.com/dkmiller/tidbits/blob/main/2024/ide-docker/vscode.Dockerfile

FROM ubuntu:24.04

RUN apt-get update && apt-get install -y curl

RUN curl -fsSL https://code-server.dev/install.sh | sh
