---
title: "Income analysis"
output:
  html_document: default
  html_notebook: default
---
```{r imports, include=FALSE, message=FALSE}
library(ggvis)
library(lubridate)
library(tidyverse)
```

Let's import the data (downloaded from Chase bank):
```{r importdata, warning=FALSE, message=FALSE}
transactions <- read_csv('/Users/dm635/Downloads/Chase3168_Activity_20180101.csv') %>%
  mutate(Date = as.POSIXct(`Posting Date`, format='%m/%d/%Y'))
```

What's the obvious first thing to track? Plot money over time.
```{r plotstuff}
transactions %>%
  ggvis(~Date, ~Balance) %>%
  layer_points
```

Now we'll split the data into three categories: just after we merged our accounts, and then two subcategories: before Microsoft, and after Microsoft.
```{r definetables}
after.merge <- transactions %>% filter(Date > as.Date('2017-01-20')) 
before.msft <- after.merge %>% filter(Date < as.Date('2017-06-12'))
after.msft <- after.merge %>% filter(Date > as.Date('2017-07-12'))
```


Let's try potting savings per month.
```{r roundmonth}
transactions %>% 
  mutate(Month = floor_date(Date, unit = 'months')) %>%
  group_by(Month) %>%
  summarize(Savings = sum(Amount)) %>%
  ggvis(~Month, ~Savings) %>%
  layer_points
```
There's a lot of noise, but hopefully we'll be saving (after tithing) $3k / month.
