name: huggingface-reddit

channels:

- defaults
# https://discuss.huggingface.co/t/problem-installing-using-conda/5518
- conda-forge
- pytorch

dependencies:

- cudatoolkit=11.0
- python=3.8
- transformers
- pip
- pytorch
- pip:
  - accelerate
  - datasets
  - protobuf
  - praw
  - scikit-learn
  - sentencepiece
