[project]
name = "ml-schemas"
readme = "README.md"
version = "0.0.1"
requires-python = ">=3.12,<3.14"
dependencies = []
[project.optional-dependencies]
dev = [
    "pytest==8.3.4",
    "ruff==0.9.4",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
