[project]
name = "api"
version = "0.0.0"
requires-python = "~=3.11"
dependencies = [
    "litestar[opentelemetry,standard]==2.4.4"
]

[project.optional-dependencies]
dev = [
    "isort==5.12.0",
        "ruff==0.1.8",
]
