[project]
name = "oryx"
version = "0.0.0"
dependencies = [
    # Sadly, does not work.
    # "oryx-core @ file:///{$PROJECT_ROOT}/oryx-core/"
    "oryx-core>=0.0.0",
]

[tool.setuptools.packages.find]
where = ["src/"]
include = ["oryx"]
