kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: workspaces-role
subjects:
- kind: ServiceAccount
  name: workspaces-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: workspaces-role
  apiGroup: rbac.authorization.k8s.io
