kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: workspaces-role
rules:
- apiGroups:
  - ''
  - apps
  resources:
  - deployments
  - pods
  - services
  # TODO: add more from
  # https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles
  verbs:
  - create
  - delete
  - get
  - list
