apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspaces
  labels:
    app: workspaces
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workspaces
  template:
    metadata:
      labels:
        app: workspaces
    spec:
      # https://stackoverflow.com/a/44510154
      # https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
      serviceAccountName: workspaces-account
      containers:
      - name: workspaces
        image: ptah://server
        env:
        - name: WORKSPACE_VARIANTS
          value: |
            - name: code
              docker_image: ptah://vscode
              container_args:
              - code-server
              - --bind-addr
              - 0.0.0.0:{{port}}
              - --auth
              - none
              readiness: /healthz
            - name: jupyter
              docker_image: ptah://jupyterlab
              container_args:
              - jupyter
              - lab
              - --allow-root
              - --ip=0.0.0.0
              - --port={{port}}
              - --IdentityProvider.token=''
              readiness: /api
        ports:
        - containerPort: 8000
