files:
  model_state_file: model.pth
  review_json: /src/tidbits/2020/2020-05-08_nlp-pytorch/yelp-dataset/yelp_academic_dataset_review.json
  sample_size: 10
  save_dir: model_storage/ch3/yelp/
  vectorizer_file: vectorizer.json
hyperparameters:
  frequency_cutoff: 25
  batch_size: 128
  early_stopping_criteria: 5
  learning_rate: 0.001
  num_epochs: 100
  seed: 1337
