compute:
  gpu: true  
files:
  model_state_file: model.onnx
  review_json: /src/tidbits/2020/2020-05-08_nlp-pytorch/yelp-dataset/yelp_academic_dataset_review.json
  sample_size: 2000000
  log_dir: tensorboard-runs
hyperparameters:
  frequency_cutoff: 25
  batch_size: 128
  early_stopping_criteria: 5
  learning_rate: 0.001
  num_epochs: 100
  seed: 1337
  max_features: 10000
