name: pt-lightning
channels:
- pytorch
- conda-forge
dependencies:
- cudatoolkit>=10.2.89
- pip>=20.2.2
- python=3.7
- pytorch>=1.6.0
- pytorch-lightning>=0.8.5
- tensorboard>=2.3.0
- torchvision>=0.2.1
- pip:
  - azureml-core
  - pyconfigurableml[munch]>=0.4.0
  # Sadly, `pip install` from here isn't working.
  # - git+git://github.com/dkmiller/pytorch-lightning.git@cb986e7422bfdcfda6779ead90f57c43004a0007
