name: hydra-pl

channels:
- defaults
- conda-forge
- pytorch

dependencies:
# Sadly, installing e.g. cudatoolkit, pytorch, pytorch-lightning via Conda
# causes the resulting job to not recognize the GPU.

- pip==20.3.3

# Sadly, Python 3.8 doesn't "play nicely" with the torchvision library.
- python=3.8

- pip:
  - azureml-mlflow==1.19.0
  - black==20.8b1
  - hydra-core==1.0.4
  - pytorch-lightning==1.1.4
  - torchvision==0.8.2
