name: hydra-pl

channels:
- defaults
- conda-forge
- pytorch

dependencies:
# Sadly, AML's "canonical" Docker images only support up to CUDA 10.2.
- cudatoolkit=10.2
- pip==20.3.3
- pytorch==1.7.1
- pytorch-lightning==1.1.1
# Sadly, Python 3.8 doesn't "play nicely" with the torchvision library.
- python=3.7
- torchvision

- pip:
  - azureml-mlflow==1.19.0
  - black==20.8b1
  - hydra-core==1.0.4
