name: nlp
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.7
  - pip>=20.0.2
  - pandas>=1.0.3
  - pytest>=5.4.2
  - pytorch>=1.5.0
  - pyyaml>=5.3.1
  - scipy>=1.4.1
  - torchvision>=0.6.0
  - pip:
    - bidict>=0.11.0
