name: nlp
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.7
  - pip>=20.0.2
  - onnx>=1.1.1
  - pandas>=1.0.3
  - pylint>=2.5.2
  - pytest>=5.4.2
  - pytorch==1.5.0
  - pyyaml>=5.3.1
  - scikit-learn>=0.22.1
  - scipy>=1.4.1
  - tensorboard>=1.15.0
  - torchvision>=0.6.0
  - wheel>=0.34.2
  - pip:
    - bidict>=0.11.0
    - onnxruntime>=1.3.0
    - typeguard>=2.7.1
