name: nlp
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - gensim>=3.8.0
  - nltk>=3.4.5
  - matplotlib>=3.2.1
  - pandas>=1.0.3
  - pylint>=2.4.4
  - pytest>=5.4.1
  - pytorch>=1.4.0
  - scikit-learn>=0.22.1
