apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: ui:${ptah}
        env:

        # Uncomment these to debug OpenTelemetry connectivity issues.
        - name: GRPC_VERBOSITY
          value: debug
        - name: GRPC_TRACE
          value: http,call_error,connectivity_state

        # TODO: how do we not duplicate this?
        - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
          # https://prometheus.io/docs/prometheus/latest/querying/api/
          # TODO: this value is probably not correct?
          value: http://prometheus-server:80/api/v1/otlp/v1/metrics
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://grafana-tempo:4317
        - name: OTEL_TRACES_EXPORTER
          value: console,otlp
        - name: OTEL_METRICS_EXPORTER
          value: console,otlp
        - name: OTEL_INSTRUMENTATION_HTTP_CAPTURE_HEADERS_SERVER_REQUEST
          value: .*
        - name: OTEL_INSTRUMENTATION_HTTP_CAPTURE_HEADERS_SERVER_RESPONSE
          value: .*
        ports:
        - containerPort: 8501
        # https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-liveness-command
        # https://loft.sh/blog/kubernetes-readiness-probes-examples-and-common-pitfalls/
        # https://kubebyexample.com/learning-paths/application-development-kubernetes/lesson-4-customize-deployments-application-2
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8501

        # TODO: bring this back.
        # livenessProbe:
        #   exec:
        #     command:
        #     - /src/liveness.sh
        #   initialDelaySeconds: 6
        #   periodSeconds: 6
        #   # This needs a long timeout b/c the prime counting is slow.
        #   timeoutSeconds: 45
