apiVersion: apps/v1
kind: Deployment
metadata:
  name: chronon
spec:
  selector:
    matchLabels:
      app: chronon
  template:
    metadata:
      labels:
        app: chronon
    spec:
      containers:
      - image: ezvz/chronon@sha256:a3f6b5e1aa85bb23269ebd67fc7e4b0fb2d0cf3e53bc2a45abdc23c95769415c
        name: chronon
        command:
        - bash 
        - -c 
        - spark-shell -i scripts/data-loader.scala && tail -f /dev/null
        env:
        - name: USER
          value: root
        - name: SPARK_SUBMIT_PATH
          value: spark-submit
        - name: PYTHONPATH
          value: /srv/chronon
        - name: SPARK_VERSION
          value: 3.1.1
        - name: JOB_MODE
          value: local[*]
        - name: PARALLELISM
          value: '2'
        - name: EXECUTOR_MEMORY
          value: 1G
        - name: EXECUTOR_CORES
          value: '1'
        - name: DRIVER_MEMORY
          value: 1G
        - name: CHRONON_LOG_TABLE
          value: default.chronon_log_table
        - name: CHRONON_ONLINE_CLASS
          value: ai.chronon.quickstart.online.ChrononMongoOnlineImpl
        - name: CHRONON_ONLINE_ARGS
          value: >
            -Zuser=admin
            -Zpassword=admin
            -Zhost=mongodb
            -Zport=27017
            -Zdatabase=admin
        ports:
        - containerPort: 4040
          name: chronon

---

kind: Service
apiVersion: v1
metadata:
  name: chronon-service
spec:
  selector:
    app: chronon
  ports:
  - port: 4040
