apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - image: confluentinc/cp-zookeeper:7.8.0
        name: zookeeper
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: '2181'
        - name: ZOOKEEPER_TICK_TIME
          value: '2000'
        ports:
        - containerPort: 2181
          name: zookeeper

---

kind: Service
apiVersion: v1
metadata:
  name: zookeeper-service
spec:
  selector:
    app: zookeeper
  ports:
  # https://stackoverflow.com/a/61452441
  - port: 22181
    targetPort: 2181
