seed: 42

model:
  image_size: 28
  color_range: 64
  hyperparam_1: 3
  learning_rate: 0.001

dataset:
  download: true
  root: .

dataloader:
  batch_size: 32

trainer:
  gpus: 0
  log_every_n_steps: 200
  max_epochs: 10
  num_nodes: 1
