seed: 42

model:
  image_size: 28
  color_range: 64
  hyperparam_1: 3
  learning_rate: 0.001

dataloader:
  batch_size: 32

hydra:
  run:
    dir: .

defaults:
- hydra/job_logging: colorlog
- hydra/hydra_logging: colorlog
- dataset: local
- trainer: debug
